--
-- PostgreSQL database dump
--

\restrict 7oVh1L8kU0bPaAFwOb4jxIX7HdZqcBa62W0qPBaskdG6O3eMKKLntbqsKyLG7El

-- Dumped from database version 17.10 (Ubuntu 17.10-1.pgdg24.04+1)
-- Dumped by pg_dump version 17.10 (Ubuntu 17.10-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


--
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_logs (
    audit_log_id uuid NOT NULL,
    action character varying(100) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(1000),
    entity_id character varying(255),
    entity_type character varying(100),
    error_message character varying(500),
    ip_address character varying(50),
    new_value jsonb,
    old_value jsonb,
    status character varying(20) NOT NULL,
    tenant_id uuid,
    user_agent character varying(500),
    user_email character varying(255),
    user_id uuid,
    user_role character varying(100)
);


--
-- Name: blacklisted_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.blacklisted_tokens (
    blacklisted_token_id bigint NOT NULL,
    expiry_date timestamp(6) with time zone NOT NULL,
    token character varying(64) NOT NULL
);


--
-- Name: blacklisted_tokens_blacklisted_token_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.blacklisted_tokens ALTER COLUMN blacklisted_token_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blacklisted_tokens_blacklisted_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_messages (
    message_id uuid NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    feedback_text character varying(1000),
    rated_at timestamp(6) without time zone,
    rating smallint,
    role character varying(20) NOT NULL,
    session_id uuid NOT NULL,
    source_chunks jsonb,
    tenant_id uuid NOT NULL,
    tokens_used integer,
    user_id uuid
);


--
-- Name: chat_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_sessions (
    session_id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    ended_at timestamp(6) without time zone,
    last_message_at timestamp(6) without time zone,
    started_at timestamp(6) without time zone NOT NULL,
    status character varying(30) NOT NULL,
    tenant_id uuid NOT NULL,
    title character varying(500),
    total_messages integer,
    total_tokens_used integer,
    updated_at timestamp(6) without time zone,
    user_id uuid NOT NULL
);


--
-- Name: chatbot_configs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chatbot_configs (
    config_id uuid NOT NULL,
    bot_name character varying(100),
    created_at timestamp(6) without time zone NOT NULL,
    embedding_provider character varying(20) DEFAULT 'GEMINI'::character varying,
    fallback_message text,
    is_active boolean NOT NULL,
    language character varying(10),
    max_message_length integer,
    max_messages_per_day integer,
    chat_mode character varying(20) DEFAULT 'BALANCED'::character varying,
    session_timeout_minutes integer,
    similarity_threshold double precision DEFAULT 0.7,
    tenant_id uuid NOT NULL,
    top_k integer DEFAULT 7,
    updated_at timestamp(6) without time zone,
    updated_by uuid,
    welcome_message text
);


--
-- Name: departments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.departments (
    department_id integer NOT NULL,
    code character varying(50) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255),
    is_active boolean NOT NULL,
    name character varying(255) NOT NULL,
    tenant_id uuid NOT NULL,
    updated_at timestamp(6) without time zone
);


--
-- Name: departments_department_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.departments ALTER COLUMN department_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departments_department_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: document_categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_categories (
    category_id uuid NOT NULL,
    code character varying(100) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by uuid,
    description text,
    is_active boolean NOT NULL,
    name character varying(255) NOT NULL,
    parent_id uuid,
    tenant_id uuid NOT NULL,
    updated_at timestamp(6) without time zone
);


--
-- Name: document_chunks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_chunks (
    document_chunk_id uuid NOT NULL,
    accessible_departments jsonb,
    accessible_roles jsonb,
    category_id uuid,
    chunk_index integer NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    document_id uuid NOT NULL,
    embedding public.vector(3072),
    embedding_model character varying(100),
    keywords jsonb,
    minimum_role_level integer DEFAULT 4 NOT NULL,
    owner_department_id integer,
    tag_ids jsonb,
    tenant_id uuid NOT NULL,
    token_count integer,
    version_id uuid,
    visibility character varying(30)
);


--
-- Name: document_summaries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_summaries (
    summary_id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    document_id uuid NOT NULL,
    error_message character varying(500),
    generated_at timestamp(6) without time zone,
    key_topics jsonb,
    language character varying(10),
    model_used character varying(100),
    status character varying(30) NOT NULL,
    summary_text text,
    tenant_id uuid NOT NULL,
    token_used integer,
    updated_at timestamp(6) without time zone
);


--
-- Name: document_tag_mappings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_tag_mappings (
    document_id uuid NOT NULL,
    tag_id uuid NOT NULL
);


--
-- Name: document_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_tags (
    tag_id uuid NOT NULL,
    code character varying(100) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by uuid,
    description text,
    is_active boolean NOT NULL,
    name character varying(150) NOT NULL,
    tenant_id uuid NOT NULL,
    updated_at timestamp(6) without time zone
);


--
-- Name: document_versions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_versions (
    version_id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by uuid NOT NULL,
    document_id uuid NOT NULL,
    storage_path character varying(500) NOT NULL,
    tenant_id uuid NOT NULL,
    version_note character varying(500),
    version_number integer NOT NULL
);


--
-- Name: documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.documents (
    document_id uuid NOT NULL,
    accessible_departments jsonb,
    accessible_roles jsonb,
    active_version_id uuid,
    category_id uuid,
    chunk_count integer,
    deleted_at timestamp(6) without time zone,
    deleted_by uuid,
    description character varying(1000),
    document_title character varying(500),
    embedding_error character varying(1000),
    embedding_model character varying(100),
    embedding_status character varying(20),
    file_name character varying(255) NOT NULL,
    file_size bigint NOT NULL,
    file_type character varying(255) NOT NULL,
    is_active boolean NOT NULL,
    last_accessed_at timestamp(6) without time zone,
    minimum_role_level integer DEFAULT 4 NOT NULL,
    original_file_name text NOT NULL,
    owner_department_id integer,
    storage_path character varying(500) NOT NULL,
    tenant_id uuid NOT NULL,
    updated_at timestamp(6) without time zone,
    updated_by uuid,
    uploaded_at timestamp(6) without time zone NOT NULL,
    uploaded_by uuid NOT NULL,
    view_count bigint,
    visibility character varying(30) NOT NULL,
    CONSTRAINT documents_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['COMPANY_WIDE'::character varying, 'SPECIFIC_DEPARTMENTS'::character varying, 'SPECIFIC_ROLES'::character varying, 'SPECIFIC_DEPARTMENTS_AND_ROLES'::character varying])::text[])))
);


--
-- Name: invoices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.invoices (
    invoice_id uuid NOT NULL,
    billing_period_end timestamp(6) without time zone,
    billing_period_start timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    currency character varying(10),
    description character varying(1000),
    invoice_number character varying(50) NOT NULL,
    issued_at timestamp(6) without time zone NOT NULL,
    paid_at timestamp(6) without time zone,
    payment_transaction_id uuid,
    status character varying(30) NOT NULL,
    subscription_id uuid,
    tenant_id uuid NOT NULL,
    total_amount numeric(15,2) NOT NULL,
    updated_at timestamp(6) without time zone
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    notification_id uuid NOT NULL,
    action_url character varying(500),
    created_at timestamp(6) without time zone NOT NULL,
    is_read boolean NOT NULL,
    message text NOT NULL,
    metadata jsonb,
    read_at timestamp(6) without time zone,
    recipient_user_id uuid,
    tenant_id uuid,
    title character varying(255) NOT NULL,
    type character varying(50) NOT NULL
);


--
-- Name: onboarding_modules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.onboarding_modules (
    onboarding_module_id uuid NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by uuid NOT NULL,
    detail_file_name character varying(255),
    detail_file_path character varying(500),
    detail_file_size bigint,
    detail_file_type character varying(100),
    display_order integer NOT NULL,
    estimated_minutes integer,
    is_active boolean NOT NULL,
    required_permissions jsonb,
    summary character varying(1000),
    tenant_id uuid NOT NULL,
    title character varying(200) NOT NULL,
    updated_at timestamp(6) without time zone
);


--
-- Name: onboarding_progress; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.onboarding_progress (
    onboarding_progress_id uuid NOT NULL,
    completed boolean NOT NULL,
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    last_viewed_at timestamp(6) without time zone,
    module_id uuid NOT NULL,
    read_percent integer NOT NULL,
    tenant_id uuid NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id uuid NOT NULL
);


--
-- Name: payment_transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payment_transactions (
    payment_transaction_id uuid NOT NULL,
    amount numeric(15,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by uuid,
    currency character varying(10) NOT NULL,
    error_message character varying(1000),
    expires_at timestamp(6) without time zone,
    gateway character varying(50) NOT NULL,
    gateway_response jsonb,
    gateway_transaction_id character varying(200),
    is_auto_renewal boolean NOT NULL,
    last_webhook_at timestamp(6) without time zone,
    notes character varying(1000),
    paid_at timestamp(6) without time zone,
    qr_content character varying(500),
    qr_image_url character varying(500),
    status character varying(50) NOT NULL,
    tenant_id uuid NOT NULL,
    tier character varying(50) NOT NULL,
    transaction_code character varying(200) NOT NULL,
    updated_at timestamp(6) without time zone,
    webhook_retry_count integer NOT NULL,
    subscription_id uuid NOT NULL,
    CONSTRAINT payment_transactions_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying, 'EXPIRED'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT payment_transactions_tier_check CHECK (((tier)::text = ANY ((ARRAY['TRIAL'::character varying, 'STARTER'::character varying, 'STANDARD'::character varying, 'ENTERPRISE'::character varying])::text[])))
);


--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_tokens (
    refresh_token_id bigint NOT NULL,
    expiry_date timestamp(6) with time zone NOT NULL,
    token character varying(255) NOT NULL,
    user_id uuid
);


--
-- Name: refresh_tokens_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.refresh_tokens_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: renewal_reminders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.renewal_reminders (
    renewal_reminder_id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email_to character varying(255) NOT NULL,
    error_message character varying(500),
    qr_content text,
    remind_day integer NOT NULL,
    sent_at timestamp(6) without time zone NOT NULL,
    status character varying(30) NOT NULL,
    subscription_id uuid NOT NULL,
    tenant_id uuid NOT NULL
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    role_id integer NOT NULL,
    code character varying(50) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by uuid,
    description character varying(500),
    is_active boolean NOT NULL,
    level integer DEFAULT 4 NOT NULL,
    name character varying(100) NOT NULL,
    permissions jsonb,
    role_type character varying(20) NOT NULL,
    tenant_id uuid,
    updated_at timestamp(6) without time zone,
    CONSTRAINT roles_level_check CHECK (((level >= 1) AND (level <= 5))),
    CONSTRAINT roles_role_type_check CHECK (((role_type)::text = ANY ((ARRAY['SYSTEM'::character varying, 'FIXED'::character varying, 'CUSTOM'::character varying])::text[])))
);


--
-- Name: roles_role_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subscription_plans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subscription_plans (
    subscription_plan_id uuid NOT NULL,
    ai_model character varying(100),
    code character varying(50) NOT NULL,
    context_window_tokens integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by uuid,
    currency character varying(10),
    description character varying(500),
    display_order integer NOT NULL,
    embedding_model character varying(100),
    features character varying(500),
    is_active boolean NOT NULL,
    max_ai_tokens integer NOT NULL,
    max_api_calls integer NOT NULL,
    max_chatbot_requests integer NOT NULL,
    max_documents integer NOT NULL,
    max_rag_documents integer NOT NULL,
    max_storage_gb integer NOT NULL,
    max_users integer NOT NULL,
    monthly_price numeric(15,2) NOT NULL,
    name character varying(100) NOT NULL,
    quarterly_price numeric(15,2) NOT NULL,
    rag_chunk_size integer NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by uuid,
    yearly_price numeric(15,2) NOT NULL
);


--
-- Name: subscriptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subscriptions (
    subscription_id uuid NOT NULL,
    ai_model character varying(100),
    auto_renew boolean NOT NULL,
    billing_cycle character varying(20),
    cancellation_reason character varying(255),
    cancelled_at timestamp(6) without time zone,
    cancelled_by uuid,
    context_window_tokens integer,
    created_at timestamp(6) without time zone NOT NULL,
    created_by uuid,
    currency character varying(10),
    embedding_model character varying(50),
    end_date timestamp(6) without time zone NOT NULL,
    grace_period_days integer DEFAULT 7,
    is_trial boolean NOT NULL,
    last_payment_date timestamp(6) without time zone,
    last_payment_id character varying(255),
    max_ai_tokens bigint,
    max_api_calls integer,
    max_chatbot_requests integer,
    max_documents integer,
    max_rag_documents integer,
    max_storage_gb integer,
    max_users integer,
    next_billing_date timestamp(6) without time zone,
    notes character varying(1000),
    payment_gateway character varying(100),
    payment_method character varying(255),
    plan_id uuid,
    price numeric(10,2),
    rag_chunk_size integer,
    start_date timestamp(6) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    tenant_id uuid NOT NULL,
    tier character varying(255) NOT NULL,
    transaction_code character varying(200),
    trial_end_date timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    updated_by uuid,
    CONSTRAINT subscriptions_billing_cycle_check CHECK (((billing_cycle)::text = ANY ((ARRAY['MONTHLY'::character varying, 'QUARTERLY'::character varying, 'YEARLY'::character varying])::text[]))),
    CONSTRAINT subscriptions_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'EXPIRED'::character varying, 'CANCELLED'::character varying, 'SUSPENDED'::character varying, 'GRACE_PERIOD'::character varying])::text[]))),
    CONSTRAINT subscriptions_tier_check CHECK (((tier)::text = ANY ((ARRAY['TRIAL'::character varying, 'STARTER'::character varying, 'STANDARD'::character varying, 'ENTERPRISE'::character varying])::text[])))
);


--
-- Name: tenants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tenants (
    tenant_id uuid NOT NULL,
    address character varying(500),
    company_size character varying(50),
    contact_email character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    inactive_at timestamp(6) without time zone,
    is_trial boolean NOT NULL,
    logo_url character varying(512),
    marked_for_deletion boolean DEFAULT false NOT NULL,
    name character varying(255) NOT NULL,
    rejection_reason character varying(500),
    representative_name character varying(100),
    representative_phone character varying(20),
    representative_position character varying(100),
    request_message character varying(1000),
    requested_at timestamp(6) without time zone,
    reviewed_at timestamp(6) without time zone,
    reviewed_by uuid,
    status character varying(255) NOT NULL,
    subscription_id uuid,
    trial_used boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    version bigint,
    website character varying(255),
    CONSTRAINT tenants_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'PENDING'::character varying, 'REJECTED'::character varying, 'SUSPENDED'::character varying])::text[])))
);


--
-- Name: tenants_datasources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tenants_datasources (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    datasource_password character varying(255) NOT NULL,
    datasource_type character varying(20) NOT NULL,
    datasource_url character varying(500) NOT NULL,
    datasource_username character varying(255) NOT NULL,
    is_active boolean NOT NULL,
    tenant_id uuid NOT NULL,
    updated_at timestamp(6) without time zone
);


--
-- Name: user_permission_grants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_permission_grants (
    grant_id uuid NOT NULL,
    granted_at timestamp(6) without time zone NOT NULL,
    granted_by uuid,
    is_active boolean NOT NULL,
    note character varying(500),
    permission character varying(100) NOT NULL,
    revoked_at timestamp(6) without time zone,
    tenant_id uuid NOT NULL,
    user_id uuid NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    user_id uuid NOT NULL,
    address character varying(500),
    contact_email character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    date_of_birth date,
    department_id integer,
    email character varying(255) NOT NULL,
    full_name character varying(255),
    is_active boolean NOT NULL,
    last_login_at timestamp(6) without time zone,
    must_change_password boolean NOT NULL,
    password character varying(255) NOT NULL,
    password_reset_session_expiry timestamp(6) without time zone,
    password_reset_session_token character varying(255),
    permissions jsonb,
    phone_number character varying(255),
    reset_password_token character varying(255),
    role_id integer NOT NULL,
    tenant_id uuid,
    token_expiry timestamp(6) without time zone,
    token_version integer DEFAULT 1 NOT NULL,
    updated_at timestamp(6) without time zone
);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (audit_log_id);


--
-- Name: blacklisted_tokens blacklisted_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.blacklisted_tokens
    ADD CONSTRAINT blacklisted_tokens_pkey PRIMARY KEY (blacklisted_token_id);


--
-- Name: chat_messages chat_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT chat_messages_pkey PRIMARY KEY (message_id);


--
-- Name: chat_sessions chat_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_sessions
    ADD CONSTRAINT chat_sessions_pkey PRIMARY KEY (session_id);


--
-- Name: chatbot_configs chatbot_configs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chatbot_configs
    ADD CONSTRAINT chatbot_configs_pkey PRIMARY KEY (config_id);


--
-- Name: departments departments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (department_id);


--
-- Name: document_categories document_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_categories
    ADD CONSTRAINT document_categories_pkey PRIMARY KEY (category_id);


--
-- Name: document_chunks document_chunks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_chunks
    ADD CONSTRAINT document_chunks_pkey PRIMARY KEY (document_chunk_id);


--
-- Name: document_summaries document_summaries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_summaries
    ADD CONSTRAINT document_summaries_pkey PRIMARY KEY (summary_id);


--
-- Name: document_tag_mappings document_tag_mappings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_tag_mappings
    ADD CONSTRAINT document_tag_mappings_pkey PRIMARY KEY (document_id, tag_id);


--
-- Name: document_tags document_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_tags
    ADD CONSTRAINT document_tags_pkey PRIMARY KEY (tag_id);


--
-- Name: document_versions document_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_versions
    ADD CONSTRAINT document_versions_pkey PRIMARY KEY (version_id);


--
-- Name: documents documents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_pkey PRIMARY KEY (document_id);


--
-- Name: invoices invoices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT invoices_pkey PRIMARY KEY (invoice_id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (notification_id);


--
-- Name: onboarding_modules onboarding_modules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.onboarding_modules
    ADD CONSTRAINT onboarding_modules_pkey PRIMARY KEY (onboarding_module_id);


--
-- Name: onboarding_progress onboarding_progress_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.onboarding_progress
    ADD CONSTRAINT onboarding_progress_pkey PRIMARY KEY (onboarding_progress_id);


--
-- Name: payment_transactions payment_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_transactions
    ADD CONSTRAINT payment_transactions_pkey PRIMARY KEY (payment_transaction_id);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (refresh_token_id);


--
-- Name: renewal_reminders renewal_reminders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.renewal_reminders
    ADD CONSTRAINT renewal_reminders_pkey PRIMARY KEY (renewal_reminder_id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (role_id);


--
-- Name: subscription_plans subscription_plans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscription_plans
    ADD CONSTRAINT subscription_plans_pkey PRIMARY KEY (subscription_plan_id);


--
-- Name: subscriptions subscriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscriptions_pkey PRIMARY KEY (subscription_id);


--
-- Name: tenants_datasources tenants_datasources_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenants_datasources
    ADD CONSTRAINT tenants_datasources_pkey PRIMARY KEY (id);


--
-- Name: tenants tenants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT tenants_pkey PRIMARY KEY (tenant_id);


--
-- Name: chatbot_configs uk16f068fe2a2c5keowxrcnm18k; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chatbot_configs
    ADD CONSTRAINT uk16f068fe2a2c5keowxrcnm18k UNIQUE (tenant_id);


--
-- Name: users uk3sk50frgdspvn94x3w0uysmii; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk3sk50frgdspvn94x3w0uysmii UNIQUE (contact_email);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: departments uk6pemxu2q2c256m1uxg3ypj08v; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT uk6pemxu2q2c256m1uxg3ypj08v UNIQUE (tenant_id, code);


--
-- Name: refresh_tokens uk7tdcd6ab5wsgoudnvj7xf1b7l; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT uk7tdcd6ab5wsgoudnvj7xf1b7l UNIQUE (user_id);


--
-- Name: subscription_plans uk95fpyxycxc00w3yabipw8jrq7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscription_plans
    ADD CONSTRAINT uk95fpyxycxc00w3yabipw8jrq7 UNIQUE (code);


--
-- Name: payment_transactions uk9upyul3sb0kp8s7utapom8iev; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_transactions
    ADD CONSTRAINT uk9upyul3sb0kp8s7utapom8iev UNIQUE (transaction_code);


--
-- Name: roles ukch1113horj4qr56f91omojv8; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukch1113horj4qr56f91omojv8 UNIQUE (code);


--
-- Name: document_summaries ukfdef292g0purqkstp2t0a7krg; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_summaries
    ADD CONSTRAINT ukfdef292g0purqkstp2t0a7krg UNIQUE (document_id);


--
-- Name: refresh_tokens ukghpmfn23vmxfu3spu3lfg4r2d; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT ukghpmfn23vmxfu3spu3lfg4r2d UNIQUE (token);


--
-- Name: tenants ukh8eolq2o5fmgxjfnvbq1s2awt; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT ukh8eolq2o5fmgxjfnvbq1s2awt UNIQUE (contact_email);


--
-- Name: blacklisted_tokens ukibvoggbe8ijw4l7xyyotp5n7g; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.blacklisted_tokens
    ADD CONSTRAINT ukibvoggbe8ijw4l7xyyotp5n7g UNIQUE (token);


--
-- Name: user_permission_grants ukjik4s1sqxafpyfs9rw8i7glcv; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_permission_grants
    ADD CONSTRAINT ukjik4s1sqxafpyfs9rw8i7glcv UNIQUE (user_id, permission);


--
-- Name: invoices ukl1x55mfsay7co0r3m9ynvipd5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT ukl1x55mfsay7co0r3m9ynvipd5 UNIQUE (invoice_number);


--
-- Name: tenants_datasources ukt1658xya6ovdihl0xp4ihcm8g; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenants_datasources
    ADD CONSTRAINT ukt1658xya6ovdihl0xp4ihcm8g UNIQUE (tenant_id);


--
-- Name: onboarding_progress uq_onboarding_progress_user_module; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.onboarding_progress
    ADD CONSTRAINT uq_onboarding_progress_user_module UNIQUE (user_id, module_id);


--
-- Name: user_permission_grants user_permission_grants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_permission_grants
    ADD CONSTRAINT user_permission_grants_pkey PRIMARY KEY (grant_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: idx_audit_logs_action; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_logs_action ON public.audit_logs USING btree (action);


--
-- Name: idx_audit_logs_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_logs_created ON public.audit_logs USING btree (created_at);


--
-- Name: idx_audit_logs_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_logs_tenant ON public.audit_logs USING btree (tenant_id);


--
-- Name: idx_audit_logs_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_logs_user ON public.audit_logs USING btree (user_id);


--
-- Name: idx_chat_messages_role; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chat_messages_role ON public.chat_messages USING btree (role);


--
-- Name: idx_chat_messages_session; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chat_messages_session ON public.chat_messages USING btree (session_id);


--
-- Name: idx_chat_messages_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chat_messages_tenant ON public.chat_messages USING btree (tenant_id);


--
-- Name: idx_chat_sessions_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chat_sessions_status ON public.chat_sessions USING btree (status);


--
-- Name: idx_chat_sessions_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chat_sessions_tenant ON public.chat_sessions USING btree (tenant_id);


--
-- Name: idx_chat_sessions_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chat_sessions_user ON public.chat_sessions USING btree (user_id);


--
-- Name: idx_chunk_document; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chunk_document ON public.document_chunks USING btree (document_id);


--
-- Name: idx_chunk_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chunk_tenant ON public.document_chunks USING btree (tenant_id);


--
-- Name: idx_chunks_embedding_cosine; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chunks_embedding_cosine ON public.document_chunks USING hnsw (((embedding)::public.halfvec(3072)) public.halfvec_cosine_ops);


--
-- Name: idx_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_created_at ON public.payment_transactions USING btree (created_at);


--
-- Name: idx_doc_categories_parent; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_doc_categories_parent ON public.document_categories USING btree (parent_id);


--
-- Name: idx_doc_categories_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_doc_categories_tenant ON public.document_categories USING btree (tenant_id);


--
-- Name: idx_doc_summaries_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_doc_summaries_tenant ON public.document_summaries USING btree (tenant_id);


--
-- Name: idx_doc_tags_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_doc_tags_tenant ON public.document_tags USING btree (tenant_id);


--
-- Name: idx_doc_versions_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_doc_versions_created ON public.document_versions USING btree (document_id, version_number);


--
-- Name: idx_doc_versions_document; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_doc_versions_document ON public.document_versions USING btree (document_id);


--
-- Name: idx_doc_versions_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_doc_versions_tenant ON public.document_versions USING btree (tenant_id);


--
-- Name: idx_invoices_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_invoices_status ON public.invoices USING btree (status);


--
-- Name: idx_invoices_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_invoices_tenant ON public.invoices USING btree (tenant_id);


--
-- Name: idx_notifications_recipient; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_recipient ON public.notifications USING btree (recipient_user_id);


--
-- Name: idx_notifications_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_tenant ON public.notifications USING btree (tenant_id);


--
-- Name: idx_onboarding_modules_tenant_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_onboarding_modules_tenant_active ON public.onboarding_modules USING btree (tenant_id, is_active);


--
-- Name: idx_onboarding_modules_tenant_order; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_onboarding_modules_tenant_order ON public.onboarding_modules USING btree (tenant_id, display_order);


--
-- Name: idx_onboarding_progress_module; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_onboarding_progress_module ON public.onboarding_progress USING btree (module_id);


--
-- Name: idx_onboarding_progress_tenant_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_onboarding_progress_tenant_user ON public.onboarding_progress USING btree (tenant_id, user_id);


--
-- Name: idx_permission_grants_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_permission_grants_tenant ON public.user_permission_grants USING btree (tenant_id);


--
-- Name: idx_permission_grants_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_permission_grants_user ON public.user_permission_grants USING btree (user_id);


--
-- Name: idx_renewal_reminders_subscription; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_renewal_reminders_subscription ON public.renewal_reminders USING btree (subscription_id);


--
-- Name: idx_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_status ON public.payment_transactions USING btree (status);


--
-- Name: idx_subscription_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_subscription_id ON public.payment_transactions USING btree (subscription_id);


--
-- Name: idx_tenant_visibility; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tenant_visibility ON public.documents USING btree (tenant_id, visibility);


--
-- Name: idx_transaction_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_transaction_code ON public.payment_transactions USING btree (transaction_code);


--
-- Name: idx_uploaded_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_uploaded_at ON public.documents USING btree (uploaded_at);


--
-- Name: refresh_tokens fk1lih5y2npsf8u5o3vhdb9y0os; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk1lih5y2npsf8u5o3vhdb9y0os FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: payment_transactions fkeok09dfg0rkqqwpid9hgkymq5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_transactions
    ADD CONSTRAINT fkeok09dfg0rkqqwpid9hgkymq5 FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(subscription_id);


--
-- Name: document_tag_mappings fkkxqkt3a2j8qdetqhjn9y6yo67; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_tag_mappings
    ADD CONSTRAINT fkkxqkt3a2j8qdetqhjn9y6yo67 FOREIGN KEY (document_id) REFERENCES public.documents(document_id);


--
-- Name: document_tag_mappings fkn13nvo1v1m9a3e8dvm4j8y0ve; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_tag_mappings
    ADD CONSTRAINT fkn13nvo1v1m9a3e8dvm4j8y0ve FOREIGN KEY (tag_id) REFERENCES public.document_tags(tag_id);


--
-- PostgreSQL database dump complete
--

\unrestrict 7oVh1L8kU0bPaAFwOb4jxIX7HdZqcBa62W0qPBaskdG6O3eMKKLntbqsKyLG7El

